### ISSUE TITLE
Spotify

### ISSUE THREAD

**Issue by oceanagain** [dromzeh/discord-custom-stream-status#1]
Is it possible to make it so it shows I'm also listening to Spotify. Like it would say "Listening to Spotify", but the online status would be the purple streaming icon. I think that would make this perfect

**Comment by dromzeh** [comment]
> Is it possible to make it so it shows I'm also listening to Spotify. Like it would say "Listening to Spotify", but the online status would be the purple streaming icon. I think that would make this perfect

I don't think that's possible sadly, just tried it out myself with different methods and it seems `streamname` can't be empty else there the streaming status will not appear & empty characters don't work either.
It also seems the *"Streaming `streamname`"* has priority over the *'Listening to spotify'* status.
If I find out a way to do it I will mention it here in this issue.
